apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deploy-role
  namespace: devops
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments","pods","services","replicasets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["secrets","configmaps"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-binding
  namespace: devops
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: devops
roleRef:
  kind: Role
  name: jenkins-deploy-role
  apiGroup: rbac.authorization.k8s.io

